### ISSUE TITLE
Packs not showing up

### ISSUE THREAD

**Issue by thecoyotejester** [mlntn/pack-o-bot#9] opened 2017-08-18 19:27 UTC
I downloaded and ran Pack-O-Bot while I had HS running. Opened a pack of KFT and it did not show up in my list. 
I closed and reopened HS, bought a pack and opened it. Still nothing.
Pack-O-Bot never said anything other than "Watching for packs..." either time.

**Comment by mlntn** [comment] 2017-08-18 19:44
Are you running pack-o-bot on Windows or OSX?

**Comment by thecoyotejester** [comment] 2017-08-18 22:03
Windows 10 v.1703

**Comment by FitzcairnHS** [comment] 2017-12-07 20:30
I have the same problem on windows 10 (64 bits)

**Comment by geraldhiller** [comment] 2017-12-07 21:08
We had a bug on the server that we've fixed now.

**Comment by FitzcairnHS** [comment] 2017-12-08 23:29
I'm sorry it's still doesnt work :/

**Comment by geraldhiller** [comment] 2017-12-11 08:49
Ok. Did you close pack-o-bot and hearthstone and then reopen pack-o-bot first? Also how fast did you add packs? We've had some issues testing ourselves when we're opening packs fast, but we couldn't reproduce issues when opening packs more slowly. 

Another thought: Considering you didn't mention an error message, but rather describes that pack-o-bot won't find packs, this strongly suggests, that pack-o-bot doesn't find the log files. If I recall correctly, we've hard-coded the application paths into this version. So it wouldn't work if you've installed Hearthstone into any other directory.

**Comment by FitzcairnHS** [comment] 2017-12-11 15:46
Yes i closed and reponed packobot and i was opening packs slowly. I didn't get error message and i don't know where is the log file but now that you are talking about it hearthstone is installed in another directory so it would be the problem but it wasnt mentioned on the install. I have a special hard drive specially for video games so i wont change the path maybe you should add a window during the installation who ask the folder game directory :)

**Comment by geraldhiller** [comment] 2017-12-11 18:02
Yes and we will. It's on our list. We just didn't find the time to do it yet. Apologies that this particular build of Pack-o-Bot is unusable for you.

**Closed as completed by geraldhiller** 2017-12-11 18:02 UTC

**Comment by FitzcairnHS** [comment] 2017-12-11 19:05
I understand don't worry that's ok we really appreciate your effort to the gamers community on your free time that's nice of you and i'm glad if i can help on tests reviews i helped sometime on github when i could on other software like a regular user because i dont have any skills about dev (soundswitch and hs dev tracker for example). Glad we found where the problem come from so i'll be patient for a new version later. Keep up the good work mate :)

**Comment by mlntn** [comment] 2017-12-12 16:47
@FitzcairnHS We just released a version of pack-o-bot that allows the user to set the install directory. @wfentress did all the heavy lifting on this, so thanks to them!

**Comment by FitzcairnHS** [comment] 2017-12-12 18:51
Oh nice ! You are fast ! I don't have any packs to open right now but when i'll get some i will try and let you know if it's working for me too :)
