### ISSUE TITLE
On startup, the application opens an empty second window - 0.3.2

### ISSUE THREAD

**Issue by Kopert** [mlntn/pack-o-bot#26] opened 2020-04-07 18:50 UTC
Just updated to 0.3.2. When the application starts, the main window shows up, then a second window - empty with a menu bar - opens up. It can be closed independently with no effect. See attached screenshot.

![packobot](https://user-images.githubusercontent.com/26443632/78707767-6ece1700-78e7-11ea-91b4-c92c55e68a3c.PNG)

**Comment by davidschwegler** [comment] 2020-04-07 20:40
Perhaps 0.3.1 was zipped instead of 0.3.2? I have the same issue after downloading 0.3.2, and in the taskbar it says 0.3.1...

![image](https://user-images.githubusercontent.com/4198124/78717354-535a1080-78d5-11ea-859e-b9af9d48fda7.png)

**Comment by Ekkstein** [comment] 2020-04-07 23:27
Hey David, the version is ok. It's just showing the wrong one in the tray menu. I have already  fixed it and will release the new version tomorrow. The issue with the empty window is also  resolved and will be part of the new release tomorrow. Thank you for reporting those issues.

**Comment by Ekkstein** [comment] 2020-04-08 21:14
I just released version 0.3.3. The issue is fixed there.

**Closed as completed by Ekkstein** 2020-04-08 21:14 UTC
